apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-queue-auth
  namespace: jjfunckeda
spec:
  secretTargetRef:
  - parameter: connection
    name: queue-connection-secret
    key: connection-string
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-queue-scaledobject
  namespace: jjfunckeda
spec:
  scaleTargetRef:
    name: jjfunckeda-http
  triggers:
  - type: azure-queue
    metadata:
      # Required
      queueName: jjqueue
      # Optional, required when pod identity is used
      accountName: jjakstestqueue
      # Optional: connection OR authenticationRef that defines connection
      #connectionFromEnv: STORAGE_CONNECTIONSTRING_ENV_NAME # Default: AzureWebJobsStorage. Reference to a connection string in deployment
      # or authenticationRef as defined below
      #
      # Optional
      queueLength: "5" # default 5
    authenticationRef:
      name: azure-queue-auth # authenticationRef would need either podIdentity or define a connection parameter      