apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: lb-scaledobject
  namespace: jjfunckeda
  labels:
    app: jjfunckeda-http
    deploymentName: jjfunckeda-http
spec:
  scaleTargetRef:
    deploymentName: jjfunckeda-http
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: azure-monitor
    metadata:
      resourceURI: Microsoft.ContainerService/managedClusters/azureMonitorCluster
      tenantId: 5bf07991-ef59-43e0-861c-ab35a6cfc932
      subscriptionId: 82fb79bf-ee69-4a57-a76c-26153e544afe
      resourceGroupName: jjakstest-rg
      metricName: kube_pod_status_ready
      metricFilter: namespace eq 'jjfunckeda'
      metricAggregationInterval: "0:1:0"
      metricAggregationType: Average
      targetValue: "1"