controller:
  service:
    loadBalancerIP: 10.4.2.250
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      kubernetes.io/ingress.class: nginx-internal
    nodeSelector:
      "kubernetes.io/os": linux