kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-zrs
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
parameters:
  storageaccounttype: Premium_ZRS
  kind: Managed
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-zrs
  resources:
    requests:
      storage: 5Gi