apiVersion: apps/v1
kind: Deployment
metadata:
  name: jjlinuxdisk
spec:
  selector:
    matchLabels:
      app: jjlinuxdisk
  template:
    metadata:
      labels:
        app: jjlinuxdisk
    spec:
      containers:
      - name: jjlinuxdisk
        image: nginx   
        resources:
          limits:
            memory: "128M"
            cpu: "500m"
        volumeMounts:
          - mountPath: "/mnt/azure"
            name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azure-managed-disk
