apiVersion: batch/v1
kind: CronJob
metadata:
  name: jjcronjob
  namespace: jjapi
spec:
  # runs every 5 minute
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello JJ
          restartPolicy: OnFailure