trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - bash: echo "A1"
  - job: A2
    steps:
    - bash: echo "A2"
- stage: B
  jobs:
  - job: B1
    steps:
    - bash: echo "B1"
  - job: B2
    steps:
    - bash: echo "B2"
