name: jjwebapicore

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    -  src-webapi/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: CompileAndCheck
    displayName: Compile and check code
    steps:      
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: 'src-webapi/jjwebapicore/**/*.csproj'
        arguments: '--configuration Release'
        workingDirectory: 'src-webapi/jjwebapicore'
  - job: Publish
    steps:
    - bash: echo test

- stage: Deploy to TEST
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web
    pool:
      vmImage: 'Ubuntu-latest'
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
  - job: B1
    steps:
    - bash: echo "B1"
      displayName: B1 popis
  - job: B2
    steps:
    - bash: echo "B2"
