name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    -  src-webui/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  subscription: 'JJ Microsoft Azure Internal Consumption (82fb79bf-ee69-4a57-a76c-26153e544afe)'
  acr: '{"loginServer":"jjakscontainers.azurecr.io", "id" : "/subscriptions/82fb79bf-ee69-4a57-a76c-26153e544afe/resourceGroups/jjmicroservices-rg/providers/Microsoft.ContainerRegistry/registries/jjakscontainers"}'

stages:
- stage: Build
  jobs:
  - job: CompileAndCheck
    displayName: Compile and check code
    steps:      
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: 'src-webui/jjwebcore/**/*.csproj'
        arguments: '--configuration Release'
        workingDirectory: 'src-webui/jjwebcore'

  - job: Publish
    displayName: Publish to ACR
    dependsOn: CompileAndCheck
    steps:
    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        azureSubscription: $(subscription)
        azureContainerRegistry: $(acr)
        dockerFile: 'src-webui/jjwebcore/Dockerfile'
        defaultContext: False
        context: 'src-webui'
        imageName: 'jjwebcore:$(Build.BuildNumber)'
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: $(subscription)
        azureContainerRegistry: $(acr)
        action: 'Push an image'
        imageName: 'jjwebcore:$(Build.BuildNumber)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish HELM charts to drop'
      inputs:
        PathtoPublish: 'src-webui/jjwebcore/charts'

- stage: DeployTEST
  displayName: Deploy to TEST
  dependsOn: Build
  jobs:
    - deployment: DeployTESTAKS
      displayName: Deploy to AKS
      pool:
        vmImage: $(vmImageName)
      environment: 'jjaks.TEST'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: drop
                path: $(Pipeline.Workspace)/drop
            - task: HelmDeploy@0
              displayName: 'helm upgrade'
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceConnection: 'jjaks-admin'
                namespace: default
                command: upgrade
                chartType: FilePath
                chartPath: '$(Pipeline.Workspace)/drop/jjwebcore'
                releaseName: jjwebcore
                overrideValues: 'image.repository=jjakscontainers.azurecr.io/jjwebcore,image.tag=$(build.buildNumber),secrets.APPINSIGHTS.INSTRUMENTATIONKEY=$(appinsights),secrets.ConnectionStrings._AppConfig="$(appconfigconnection)",secrets.ASPNETCORE.ENVIRONMENT=Development'
                valueFile: '$(Pipeline.Workspace)/drop/jjwebcore/values.yaml'
                waitForExecution: false