# Default values for jjwebapicore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: jjwebapicore
replicaCount: 3
image:
  repository: jjwebapicore
  tag: stable
  pullPolicy: IfNotPresent
imagePullSecrets: []
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
service:
  type: ClusterIP
  port: 80

probes:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/api/$2"
  path: /api(/|$)(.*)
  # hosts:
  #   - chart-example.local
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
secrets:
  # Optionally specify a set of secret objects whose values
  # will be injected as environment variables by default.
  # You should add this section to a file like secrets.yaml
  # that is explicitly NOT committed to source code control
  # and then include it as part of your helm install step.
  # ref: https://kubernetes.io/docs/concepts/configuration/secret/
  #
  # This creates a secret "mysecret" and injects "mypassword"
  # as the environment variable mysecret_mypassword=password.
  # mysecret:
  #   mypassword: password
  APPINSIGHTS:
    INSTRUMENTATIONKEY: 00000000-0000-0000-0000-000000000000                        
  ConnectionStrings:
    ContactsContext: copy_sqldatabase_connectionstring
resources:
  limits:
   # limit CPU 1000m = 1CPU
   # limit memory - restart pod if hit
   cpu: 1000m
   memory: 128Mi    
  requests:
    # for allocation on node and scaling
   cpu: 100m
   memory: 128Mi
nodeSelector:
  "kubernetes.io/os": linux

tolerations: []

affinity: {}
