name: WebApi dotnet

on:
  workflow_dispatch:
    
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src-webapi

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    # TODO: Code coverage
    # https://github.com/marketplace/actions/code-coverage-summary

  publish:
    name: 'Publish to ACR'
    runs-on: ubuntu-latest
    environment: dev    
    env:
      ACR_NAME: 'jjakscontainers'
    defaults:
      run:
        shell: bash
        working-directory: src-webapi

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # TODO: login ACR using RBAC 
    # https://cloudarchitected.com/2021/09/logging-into-acr-in-github-actions/
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # TODO: Generate Build Number
    # https://github.com/marketplace/actions/build-number-generator
    - run: |
        docker build . -t ${{ env.ACR_NAME }}.azurecr.io/jjwebapicore:${{ github.sha }} -f jjwebapicore/Dockerfile
        docker push ${{ env.ACR_NAME }}.azurecr.io/jjwebapicore:${{ github.sha }}

  deploy:
    name: 'Deploy to AKS'
    runs-on: ubuntu-latest
    environment: dev    
    env:
      ACR_NAME: 'jjakscontainers'
    defaults:
      run:
        shell: bash
        working-directory: src-webapi

    # AZURE_CREDENTIALS format https://github.com/marketplace/actions/azure-login#configure-deployment-credentials
    # {"clientId":"XXX","clientSecret":"XXX","subscriptionId":"XXX","tenantId":"XXX"}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
