name: WebApi dotnet

on:
  workflow_dispatch:
    
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    name: 'Build dotnet'
    runs-on: ubuntu-latest
    environment: dev
#    env:
#      SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
    defaults:
      run:
        shell: bash
        working-directory: src-webapi/jjwebapicore

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
