name: WebApi dotnet

on:
  workflow_dispatch:
    
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# AZURE_CREDENTIALS format https://github.com/marketplace/actions/azure-login#configure-deployment-credentials
# {"clientId":"XXX","clientSecret":"XXX","subscriptionId":"XXX","tenantId":"XXX"}

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src-webapi

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    # TODO: Code coverage
    # https://github.com/marketplace/actions/code-coverage-summary

    # TODO: Generate Build Number
    # https://github.com/marketplace/actions/build-number-generator

  publish:
    name: 'Publish to ACR'
    runs-on: ubuntu-latest
    environment: dev    
    env:
      ACR_NAME: 'jjakscontainers'
    defaults:
      run:
        shell: bash
        working-directory: src-webapi

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az acr login --name ${{ env.ACR_NAME }}
        docker build . -t ${{ env.ACR_NAME }}.azurecr.io/jjwebapicore:${{ github.sha }} -f jjwebapicore/Dockerfile
        docker push ${{ env.ACR_NAME }}.azurecr.io/jjwebapicore:${{ github.sha }}

  deploy:
    name: 'Deploy to AKS'
    runs-on: ubuntu-latest
    environment: dev    
    env:
      ACR_NAME: 'jjakscontainers'
      AKS_NAME: 'jjaks'
      AKS_RG: 'jjmicroservices-rg'
      AKV_NAME: 'jjakskv'
    defaults:
      run:
        shell: bash
        working-directory: src-webapi
    needs: publish

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: ${{ env.AKV_NAME }}
        secrets: 'contactsDbConnection, appInsightsKey'
      id: kv
    # https://docs.microsoft.com/en-us/azure/developer/github/github-key-vault

    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.AKS_NAME }}
        resource-group: ${{ env.AKS_RG }}

    # https://github.com/Azure/k8s-deploy
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: './jjwebapicore/charts/jjwebapicore'
        # overrideFiles: './jjwebapicore/charts/values.yaml'
        # overrides: |     
        #   image.repository:jjakscontainers.azurecr.io/jjwebapicore
        #   image.tag:${{ github.sha }}
        #   secrets.APPINSIGHTS.INSTRUMENTATIONKEY:steps.kv.outputs.appInsightsKey
        #   secrets.ConnectionStrings.ContactsContext:steps.kv.outputs.contactsDbConnection
        helm-version: 'latest'
      id: bake

 

#    - uses: Azure/k8s-deploy@v1.2
#      with:
#        manifests: ${{ steps.bake.outputs.manifestsBundle }}