name: WebUi dotnet
# Requirements: 
#   Azure User Managed Identity with Federated credentials for GH Actions
#   Permissions: Contributor scope Resource group
#   GitHub repository secrets
#   GitHub environment secrets

on:
  workflow_dispatch:
    
  push:
    branches: 
    - master
    paths:
    - 'src-webui/**'

  pull_request:
    branches: 
    - master
    paths:
    - 'src-webui/**'

permissions:
      id-token: write
      contents: read   

jobs:

  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src-webui

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    # TODO: Code coverage
    # https://github.com/marketplace/actions/code-coverage-summary

    # TODO: Generate Build Number
    # https://github.com/marketplace/actions/build-number-generator

  publish:
    name: 'Publish to ACR'
    runs-on: ubuntu-latest
    environment: dev    
    needs: build
    defaults:
      run:
        shell: bash
        working-directory: src-webui
    if: (github.ref == 'refs/heads/master' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch')
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: OIDC Login to Azure Public Cloud (using Azure User Managed Identity)
      uses: Azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  

    - name: Push image
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
        docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/jjwebcore:${{ github.sha }} -f jjwebcore/Dockerfile
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/jjwebcore:${{ github.sha }}

  deploy:
    name: 'Deploy to AKS'
    runs-on: ubuntu-latest
    environment: dev    
    defaults:
      run:
        shell: bash
        working-directory: src-webui
    needs: publish
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: OIDC Login to Azure Public Cloud (using Azure User Managed Identity)
      uses: Azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  

    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: ${{ secrets.AKV_NAME }}
        secrets: 'appConfig, appInsightsConfig, openaiEndpoint, openaiKey'
      id: kv

    - uses: Azure/aks-set-context@v3
      with:
        cluster-name: ${{ secrets.AKS_NAME }}
        resource-group: ${{ secrets.AKS_RG }}
        admin: true

    # !!! not reflecting default working-directory
    - uses: azure/k8s-bake@v2
      with:
        renderEngine: 'helm'
        helmChart: './src-webui/jjwebcore/charts/jjwebcore'
        overrideFiles: './src-webui/jjwebcore/charts/jjwebcore/values.yaml'
        overrides: |     
          image.repository:${{ secrets.ACR_NAME }}.azurecr.io/jjwebcore
          image.tag:${{ github.sha }}
          secrets.ASPNETCORE.ENVIRONMENT:Development
          secrets.APPLICATIONINSIGHTS.CONNECTION_STRING:${{ steps.kv.outputs.appInsightsConfig }}
          secrets.ConnectionStrings._AppConfig:${{ steps.kv.outputs.appConfig }}
          secrets.AzureOpenAI._Deployment:jjconsole
          secrets.AzureOpenAI._Endpoint:${{ steps.kv.outputs.openaiEndpoint }}
          secrets.AzureOpenAI._ApiKey:${{ steps.kv.outputs.openaiKey }}
        helm-version: 'latest'
        silent: 'false'
      id: bake

    - uses: Azure/k8s-deploy@v4
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        namespace: 'jjweb'
        # strategy: canary
        # traffic-split-method: smi
        # action: deploy #deploy is the default; we will later use this to promote/reject
        # percentage: 20
        # baseline-and-canary-replicas: 1
